#########################
#####  SimplePerms  #####
#########################

# SimplePerms is the smallest Permissions plugin available.
# You can assign permissions to all players by putting it in the following list.

# Example:
#
# permissions:
# -	minecraft.command.time
# - minecraft.command.weather
# - minecraft.command.tp
# - chestsort.use

permissions: